### PR TITLE
Add support for conditional compile elements

### PR DESCRIPTION
**Pull request by evgygor**
Solving [issue #1](https://github.com/TwitchBronBron/brightscript-parser/issues/1)

### CODE REVIEW

**Comment by TwitchBronBron** [comment]
Looks good. Can you remove the yarn.lock file? I don't use yarn, so it will end up cluttering the repository and becoming stale over time.

**Comment by evgygor** [comment]
> Looks good. Can you remove the yarn.lock file? I don't use yarn, so it will end up cluttering the repository and becoming stale over time.

yarn.lock have same reason as package-lock.json.
'package-lock.json' does not disturb yarn users users and yarn.lock  does not disturb the npm users

**Comment by TwitchBronBron** [comment]
> > Looks good. Can you remove the yarn.lock file? I don't use yarn, so it will end up cluttering the repository and becoming stale over time.
> 
> yarn.lock have same reason as package-lock.json.
> 'package-lock.json' does not disturb yarn users users and yarn.lock does not disturb the npm users

I get that, but it doesn't need to be in this project.

**Comment by evgygor** [comment]
No problem, I deleted it.

**Pull request merged**
